train = [
    ('vm', 'compute'),
    ('vms', 'compute'),
    ('instance', 'compute'),
    ('virtual machine', 'compute'),
    ('VM', 'compute'),
    ('Create a vm', 'compute'),
    ('create a virtual machine', 'compute'),
    ('Spin up an instance', 'compute'),
    ('Please create a virtual machine', 'compute'),
    ('Show all VMs', 'compute'),
    ('list vms', 'compute'),
    ('list instances', 'compute'),
    ('Delete vm', 'compute'),
    ('delete vm', 'compute'),
    ('Delete instance', 'compute'),
    ('delete all vms in my cloud', 'compute'),
    ('network', 'network'),
    ('Network', 'network'),
    ('networks', 'network'),
    ('Networks', 'network'),
    ('Create a Network', 'network'),
    ('create network', 'network'),
    ('list networks', 'network'),
    ('List networks', 'network'),
    ('Show all the networks available', 'network'),
    ('Delete network', 'network'),
    ('Delete All Networks', 'network'),
    ('volumes', 'storage'),
    ('cinder', 'storage'),
    ('list volumes', 'storage'),
    ('deploy', 'deploy'),
    ('Deploy', 'deploy'),
    ('OpenStack', 'deploy'),
    ('Deploy OpenStack cloud', 'deploy'),
    ('Clean up', 'cleanup'),
    ('Restart', 'cleanup'),
    ('Reset', 'cleanup'),
    ('Who are you?', 'general'),
    ('Who created you?', 'general'),
    ('What can you do?', 'general'),
]
